### PR TITLE
Generate `build.js` only at publication time

### PR DESCRIPTION
**Pull request by thom4parisot**
It avoids having to version `build.js` in Git (so less conflicts etc.)

### CODE REVIEW

**Comment by DavidBruant** [comment]
A peine on a fini de bouffer une omelette que @oncletom fait déjà des PR !

**Comment by Yomguithereal** [comment]
Seems better indeed. Bonne "omelette du fromage". What's the use for `&& node ./index.js` in the `prepublish` script?

**Comment by thom4parisot** [comment]
Tais-toi @DavidBruant révèle pas mes secrets comme ça !

**Comment by thom4parisot** [comment]
@Yomguithereal the `&& node ./index.js` is about launching the tests from a Node perspective (after the ES6 to ES5 conversion) but… it will fail because tests are written in ES6 anyway.

I guess it should be `babel-node tests`, expecting some JSON to turn into a GEXF file. I did not realise the tests were simply outputting something to the console.

**Pull request merged**
